server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
#    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname:vbc-server}:8761/eureka/

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: file://${user.home}/config-repo
          uri: https://github.com/davidshue/config-repo
          force-pull: true
          basedir: target/config
security:
  basic:
    enabled: true
    path: /**
    real: vbc
  user:
    name: admin
    password: s3cret
    role: USER
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme