server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /admin/info
    health-check-url-path: /admin/health
#    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.server.hostname:vbc-server}:8761/eureka/

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: "file:/Users/david/workspace/config-repo"
        git:
#          uri: file://${user.home}/config-repo
          uri: https://github.com/davidshue/config-repo
          force-pull: true
          basedir: target/config
  security:
    user:
      name: admin
      password: s3cret
encrypt:
  key-store:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme