spring:
  application:
    name: switch
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
hystrix:
  command:
    default:
      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
#node:
#  ribbon:
#    ConnectTimeout: 30000
#    ReadTimeout: 600000