spring:
  application:
    name: kafka-switch
threadpool:
  queue:
    size:
      core: 50
      max: 100
      capacity: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000
        timeout:
          enabled: true
#node:
#  ribbon:
#    ConnectTimeout: 30000
#    ReadTimeout: 600000