# spring:
#   application:
#    name: eureka
server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: vbc-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
