spring:
  application:
    name: node
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http