spring:
  application:
    name: node
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http