spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30463251451-2fivpa6nnht6ncltp27c2ugruvcskig2.apps.googleusercontent.com
            client-secret: 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