spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
zuul:
  ignoredServices: '*'
  routes:
    kafka-node: /node/**
    configserver: /config/**
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15