spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
zuul:
  routes:
    kafka-node: /node/**
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15